"""Reviri API.

Run:  uvicorn main:app --host 0.0.0.0 --port 8000 --reload
Docs: http://localhost:8000/docs  (try every endpoint in the browser)
Keys: put them in backend/.env (see .env.example). That file is in .gitignore: never commit it.
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Load backend/.env before anything reads the environment. Variables already exported
# in the terminal win over the file. Tests skip it so they never touch real keys or Neon.
if not os.getenv("REVIRI_TESTING"):
    load_dotenv(Path(__file__).parent / ".env")
import asyncio
from contextlib import asynccontextmanager
from datetime import date, datetime, timedelta
from typing import List

import httpx
from fastapi import FastAPI, File, HTTPException, Request, UploadFile

import catalog
import db
import fridge
import gemini
import logic
import notify
import receipt
import recipe_gen
import rewind
from models import (
    AlertSent, AlertSettings, CookRequest, CookResponse, FridgeApplyRequest, FridgeScanResponse, GenerateRecipeRequest,
    InventoryItem, NextWeekRequest,
    NextWeekResponse, OK, PlanRequest, PlanResult, Recipe, RewindChange, RewindPreview, RewindRequest,
    ShoppingListRequest, Stats, Suggestion,
    SuggestionsResponse,
)
from store import Store

# Daily "spoils by tomorrow" text goes out at this hour (Mac's local time).
ALERT_HOUR = int(os.getenv("ALERT_HOUR", "9"))


@asynccontextmanager
async def lifespan(_app):
    task = asyncio.create_task(_daily_alerts())
    yield
    task.cancel()


app = FastAPI(title="Reviri API", lifespan=lifespan)
# DATABASE_URL = Neon's connection string. Without it, state lives in memory only.
store = Store(db.Database(os.environ["DATABASE_URL"]) if os.getenv("DATABASE_URL") else None)


@app.middleware("http")
async def save_after_changes(request: Request, call_next):
    """Every request that may have changed something is followed by one save to Neon."""
    response = await call_next(request)
    if request.method != "GET" and response.status_code < 400:
        try:
            store.save()
        except Exception as e:   # keep serving from memory; the next save retries everything
            print("[db] SAVE FAILED, changes are only in memory for now:", e)
    return response


def _inventory_view() -> List[InventoryItem]:
    today = date.today()
    items = [i.model_copy(update={"days_left": logic.days_left(i, today)})
             for i in store.inventory if i.qty_base > logic.EPS]
    return sorted(items, key=lambda i: (i.days_left, i.display_name))


def _recipe_or_404(recipe_id: str) -> Recipe:
    r = store.recipe(recipe_id)
    if r is None:
        raise HTTPException(404, "Unknown recipe: %s" % recipe_id)
    return r


@app.get("/health")
def health() -> dict:
    return {"ok": True, "gemini_key_set": gemini.has_api_key(),
            "database": "neon" if store.db is not None else "memory"}


@app.get("/recipes", response_model=List[Recipe])
def recipes():
    """The recipe book plus any recipes generated by search."""
    return store.all_recipes()


@app.post("/recipes/generate", response_model=Suggestion)
async def generate_recipe(req: GenerateRecipeRequest):
    """Search: Gemini writes a recipe for any dish name. Returned like a suggestion, so the
    app can show what it uses up and what's missing. The recipe can then be cooked or planned."""
    query = recipe_gen.normalize_name(req.name)
    key = recipe_gen.slug(query)
    if not key or len(query) > recipe_gen.MAX_NAME_LEN:
        raise HTTPException(400, "Type a dish name (up to %d characters)." % recipe_gen.MAX_NAME_LEN)
    recipe = store.generated.get(key)
    if recipe is None:
        if not gemini.has_api_key():
            raise HTTPException(503, "Recipe search needs GEMINI_API_KEY on the server.")
        try:
            recipe = await recipe_gen.generate(query)
        except recipe_gen.NotARecipe:
            raise HTTPException(422, "\"%s\" doesn't look like a dish. Try something like \"chicken alfredo\"."
                                % req.name.strip())
        except httpx.HTTPError as e:
            raise HTTPException(502, "Gemini request failed: %s %s" % (type(e).__name__, e))
        except (ValueError, KeyError, IndexError) as e:
            raise HTTPException(502, "Couldn't write that recipe: %s" % e)
        store.generated[key] = recipe
    return logic.describe_recipe(store.inventory, recipe, date.today())


@app.get("/inventory", response_model=List[InventoryItem])
def inventory():
    return _inventory_view()


@app.post("/parse-receipt", response_model=List[InventoryItem])
async def parse_receipt(file: UploadFile = File(...)):
    """Upload a receipt photo (multipart field name: file). Parsed items are added to the pantry."""
    data = await file.read()
    today = date.today()
    skipped: List[str] = []
    try:
        items = await receipt.parse_receipt(data, file.content_type or "image/jpeg", today, skipped)
    except httpx.HTTPError as e:
        raise HTTPException(502, "Gemini request failed: %s %s" % (type(e).__name__, e))
    except (ValueError, KeyError, IndexError) as e:
        raise HTTPException(502, "Could not read Gemini's answer: %s" % e)
    store.inventory.extend(items)
    store.last_receipt_skipped = skipped
    ids = {i.id for i in items}
    return [i for i in _inventory_view() if i.id in ids]


@app.get("/receipt/skipped", response_model=List[str])
def receipt_skipped():
    """Food lines from the last receipt scan that Reviri doesn't track (shown as "Not tracked")."""
    return store.last_receipt_skipped


@app.post("/scan-fridge", response_model=FridgeScanResponse)
async def scan_fridge(file: UploadFile = File(...)):
    """Upload a fridge photo (multipart field name: file). Returns PROPOSED changes:
    "update" items already in the pantry, "add" new ones, list "untracked" ones. Nothing is saved."""
    if not gemini.has_api_key():
        raise HTTPException(503, "Fridge scanning needs GEMINI_API_KEY on the server.")
    data = await file.read()
    try:
        items = await fridge.scan(data, file.content_type or "image/jpeg", store.inventory)
    except httpx.HTTPError as e:
        raise HTTPException(502, "Gemini request failed: %s %s" % (type(e).__name__, e))
    except (ValueError, KeyError, IndexError) as e:
        raise HTTPException(502, "Could not read Gemini's answer: %s" % e)
    return FridgeScanResponse(items=items)


@app.post("/fridge/apply", response_model=List[InventoryItem])
def apply_fridge(req: FridgeApplyRequest):
    """Save the fridge changes the user confirmed: each ingredient's pantry total becomes qty_base."""
    today = date.today()
    for item in req.items:
        if not catalog.is_known(item.canonical):
            raise HTTPException(400, "Unknown ingredient: %s" % item.canonical)
        if item.qty_base < 0:
            raise HTTPException(400, "Quantity can't be negative")
        logic.set_total(store.inventory, item.canonical, item.qty_base, today, item.brand)
    store.inventory = [l for l in store.inventory if l.qty_base > logic.EPS]
    return _inventory_view()


@app.post("/demo-receipt", response_model=List[InventoryItem])
def demo_receipt():
    """Adds a fixed sample receipt to the pantry. Works with no API key."""
    items = receipt.demo_items(date.today())
    store.inventory.extend(items)
    ids = {i.id for i in items}
    return [i for i in _inventory_view() if i.id in ids]


@app.put("/inventory/{item_id}", response_model=InventoryItem)
def update_item(item_id: str, body: InventoryItem):
    """Fix a quantity after a bad scan. Only qty_base is applied; 0 removes the item."""
    for lot in store.inventory:
        if lot.id == item_id:
            if body.qty_base < 0:
                raise HTTPException(400, "Quantity can't be negative")
            lot.qty_base = body.qty_base
            view = [i for i in _inventory_view() if i.id == item_id]
            return view[0] if view else lot.model_copy(update={"days_left": 0})
    raise HTTPException(404, "No such item")


@app.delete("/inventory/{item_id}", response_model=OK)
def delete_item(item_id: str, reason: str = "used"):
    """Remove an item. reason=tossed counts it as wasted on the Savings tab; reason=used doesn't."""
    if reason not in ("used", "tossed"):
        raise HTTPException(400, "reason must be used or tossed")
    if not store.remove(item_id, tossed=(reason == "tossed")):
        raise HTTPException(404, "No such item")
    return OK()


@app.post("/plan", response_model=PlanResult)
def plan(req: PlanRequest):
    """Preview leftovers and missing items for a set of meals. Nothing is saved."""
    meals = [(_recipe_or_404(p.recipe_id), p.servings) for p in req.picks if p.servings > 0]
    return logic.preview(store.inventory, meals, date.today())


@app.post("/cook", response_model=CookResponse)
def cook(req: CookRequest):
    """Commit a meal: deduct ingredients. from_suggestion=true also counts the rescued food in stats."""
    recipe = _recipe_or_404(req.recipe_id)
    if req.servings <= 0:
        raise HTTPException(400, "servings must be positive")
    today = date.today()
    out = logic.cook(store.inventory, recipe, req.servings, req.from_suggestion, today)
    store.inventory = out.lots
    store.add_saved(out.saved_g, out.saved_usd, out.saved_co2e)
    return CookResponse(
        leftovers=logic.leftovers_for(store.inventory, out.touched, today),
        stats=store.stats(today),
    )


@app.get("/suggestions", response_model=SuggestionsResponse)
def suggestions():
    """Recipes that use up perishables we already own, best first."""
    return SuggestionsResponse(
        suggestions=logic.suggest(store.inventory, store.recipes, date.today()))


@app.post("/next-week", response_model=NextWeekResponse)
def next_week(req: NextWeekRequest):
    """Plan the next N meals around what's already here and build the shopping list."""
    meals, shopping, projected, baseline = logic.plan_week(
        store.inventory, store.recipes, req.meals, date.today())
    return NextWeekResponse(meals=meals, shopping_list=shopping,
                            projected_waste_g=projected, baseline_waste_g=baseline)


@app.get("/stats", response_model=Stats)
def stats():
    return store.stats(date.today())


@app.post("/checkin", response_model=Stats)
def checkin():
    """Streak check-in, once per day. Blocked while anything in the pantry is past its date:
    the streak means "I dealt with all my food today", so expired items must be used or tossed first."""
    today = date.today()
    expired = sorted({l.display_name.lower() for l in store.expired(today)})
    if expired:
        names = expired[0] if len(expired) == 1 else ", ".join(expired[:-1]) + " and " + expired[-1]
        raise HTTPException(409, "Your %s expired. Mark %s as used or thrown away in Pantry first."
                            % (names, "it" if len(expired) == 1 else "them"))
    store.check_in(today)
    return store.stats(today)


@app.post("/demo/skip-days", response_model=List[InventoryItem])
def skip_days(days: int = 3):
    """Demo only (hidden in the app): age the pantry by `days` so food expires during the demo.
    Negative days undo a skip."""
    if days == 0 or not -30 <= days <= 30:
        raise HTTPException(400, "days must be between -30 and 30, and not 0")
    store.age(days)
    return _inventory_view()


# ---------------------------------------------------------------- rewind (Neon Time Travel)

def _with_days_left(items: List[InventoryItem]) -> List[InventoryItem]:
    today = date.today()
    view = [i.model_copy(update={"days_left": logic.days_left(i, today)}) for i in items if i.qty_base > logic.EPS]
    return sorted(view, key=lambda i: (i.days_left, i.display_name))


def _changes(then: List[InventoryItem], now: List[InventoryItem]) -> List[RewindChange]:
    totals = {}
    for side, lots in (("then", then), ("now", now)):
        for lot in lots:
            entry = totals.setdefault(lot.canonical, {"then": 0.0, "now": 0.0, "lot": lot})
            entry[side] += lot.qty_base
    return sorted((RewindChange(canonical=c, display_name=e["lot"].display_name, unit_base=e["lot"].unit_base,
                                qty_then=round(e["then"], 1), qty_now=round(e["now"], 1))
                   for c, e in totals.items() if abs(e["then"] - e["now"]) > 0.05),
                  key=lambda ch: ch.display_name)


async def _read_past(when):
    if store.db is None:
        raise HTTPException(503, "Rewind needs Neon: add DATABASE_URL to backend/.env and restart the server.")
    try:
        return await rewind.read_past(when)
    except rewind.RewindError as e:
        raise HTTPException(409, str(e))


@app.get("/rewind/preview", response_model=RewindPreview)
async def rewind_preview(minutes: int):
    """The pantry as it was `minutes` ago (Neon Time Travel), and what restoring it would change."""
    try:
        when = rewind.moment(minutes)
    except rewind.RewindError as e:
        raise HTTPException(400, str(e))
    past = await _read_past(when)
    return RewindPreview(at=when.isoformat().replace("+00:00", "Z"), minutes_ago=minutes,
                         items=_with_days_left(past.inventory), changes=_changes(past.inventory, store.inventory))


@app.post("/rewind", response_model=List[InventoryItem])
async def rewind_restore(req: RewindRequest):
    """Bring back the pantry and food totals from a previewed moment. The streak and
    settings are not rewound (the check-ins really happened)."""
    try:
        when = rewind.parse_moment(req.at)
    except rewind.RewindError as e:
        raise HTTPException(400, str(e))
    past = await _read_past(when)
    store.inventory = past.inventory
    for field, value in past.totals.items():
        setattr(store, field, value)
    return _inventory_view()      # the middleware saves this to Neon, which becomes the new present


# ---------------------------------------------------------------- text alerts (Photon)

def _alert_settings() -> AlertSettings:
    return AlertSettings(phone=store.alert_phone, enabled=store.alerts_enabled, mode=notify.mode())


async def _send(text: str) -> AlertSent:
    if not store.alert_phone:
        raise HTTPException(400, "Add your phone number in Settings first.")
    try:
        await notify.send_text(store.alert_phone, text)
    except notify.NotifyError as e:
        raise HTTPException(502, str(e))
    return AlertSent(text=text)


@app.get("/alerts", response_model=AlertSettings)
def get_alerts():
    return _alert_settings()


@app.put("/alerts", response_model=AlertSettings)
def put_alerts(body: AlertSettings):
    """Save the phone number and the daily alert switch. An empty phone turns alerts off."""
    if body.phone and body.phone.strip():
        phone = notify.normalize_phone(body.phone)
        if phone is None:
            raise HTTPException(400, "That doesn't look like a phone number. Try +1 555 123 4567.")
        store.alert_phone = phone
    else:
        store.alert_phone = None
    store.alerts_enabled = body.enabled and store.alert_phone is not None
    return _alert_settings()


def _spoil_alert(today: date):
    return notify.spoil_alert_text(store.inventory, logic.suggest(store.inventory, store.recipes, today), today)


def _neon_alert_function():
    """(url, token) of the deployed daily-alert Neon Function, or None (see neon/deploy.py)."""
    url, token = os.getenv("NEON_ALERT_URL"), os.getenv("NEON_ALERT_TOKEN")
    return (url, token) if url and token else None


@app.post("/alerts/test", response_model=AlertSent)
async def test_alert():
    """Send the daily alert right now (for testing and the demo). When the Neon Function is
    deployed, this runs it: the same code Neon's 9 AM schedule runs, inside Neon."""
    neon_fn = _neon_alert_function()
    if neon_fn is None:
        text = _spoil_alert(date.today()) or "Reviri: nothing in your pantry spoils by tomorrow. Nice work."
        return await _send(text)
    if not store.alert_phone:
        raise HTTPException(400, "Add your phone number in Settings first.")
    store.save()          # the function reads the phone number and pantry from Neon
    url, token = neon_fn
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            r = await client.post(url, params={"token": token, "force": "1"})
        body = r.json()
    except (httpx.HTTPError, ValueError) as e:
        raise HTTPException(502, "Couldn't reach the Neon Function: %s %s" % (type(e).__name__, e))
    if not body.get("sent"):
        raise HTTPException(502, "The Neon Function didn't send it: %s" % body.get("reason"))
    return AlertSent(text=body["text"])


@app.post("/alerts/shopping-list", response_model=AlertSent)
async def text_shopping_list(req: ShoppingListRequest):
    """'Text me this list': send the shopping list the app is showing."""
    return await _send(notify.shopping_list_text(req.title, req.items))


async def _daily_alerts():
    """Background loop: once a day at ALERT_HOUR, text what spoils by tomorrow (if anything does).
    Off when the Neon Function is deployed: Neon's own schedule sends it then (no double texts)."""
    if _neon_alert_function() is not None:
        print("[notify] daily alert runs as a Neon Function; the server's own loop is off")
        return
    while True:
        now = datetime.now()
        next_run = now.replace(hour=ALERT_HOUR, minute=0, second=0, microsecond=0)
        if next_run <= now:
            next_run += timedelta(days=1)
        await asyncio.sleep((next_run - now).total_seconds())
        today = date.today()
        if not (store.alerts_enabled and store.alert_phone) or store.last_alert_day == today:
            continue
        text = _spoil_alert(today)
        if text:
            try:
                await notify.send_text(store.alert_phone, text)
                store.last_alert_day = today
                store.save()
            except notify.NotifyError as e:
                print("[notify] daily alert failed:", e)


@app.post("/reset", response_model=OK)
def reset():
    """Back to the starting pantry. Use before every demo run."""
    store.reset()
    return OK()
